### ISSUE TITLE
Adding links (twitter, Facebook, email and so on and so forth)

### ISSUE THREAD

**Issue by liamcan** [strategicdata/cannold.com#7]
- [x] The links Leslie wants included are:
        

- [x] - Mobile Phone (Remember to make it work for both Local and International users)
- [x] - Skype: lcannold
- [x] - Twitter
- [x] - LinkedIn
- [x] - Facebook

**Comment by liamcan** [comment]
Then :
- [ ] Delete unnecessary code
- [ ] Check links work

**Comment by liamcan** [comment]
@adamc00 Will need a little guidance about how to add phone number in way where it's like a link and works for both local and international calls, if I work it out i'll tick this off but having trouble

**Comment by adamc00** [comment]
> add phone number in way where it's like a link

Browsers just sort this out for you. Just putting in +61 417 114 859 should work ok. If it doesn't we can look at it further.
