### ISSUE TITLE
Duplicating Sections

### ISSUE THREAD

**Issue by liamcan** [strategicdata/cannold.com#9]
- [x] Leslie would like the front section duplicated a few times for her different professions, discuss best way to achieve this

- [x] Leslie has more topics than the amount of bootstrap grids given, I've done a course on bootsrap but plain and straight I am pretty bad at understanding it thing so a hand plus some teaching could be nice

**Comment by liamcan** [comment]
@adamc00 The above stuff is a pretty good outline of what needs to be done.

**Comment by liamcan** [comment]
- [ ] I feel that the Ethicist section can be duplicated within the containers of the Author section, but may look better if it had it's own container to distinguish it from the Author section, will look into but don't know if i'll achieve this without breaking things.

- [ ] Leslie would like a showreel attached to her public speaker section, I thought best way might be to grab code from one of the movie specific pages that canvas offers, thoughts?

**Comment by liamcan** [comment]
@adamc00 This has been done except for last point, what would be best way to achieve?

**Comment by adamc00** [comment]
> Leslie would like a showreel attached to her public speaker section, I thought best way might be to grab code from one of the movie specific pages that canvas offers, thoughts?

That seems like a good idea. Give it a go?
